# Generated by Django 4.2.9 on 2024-02-29 07:41

from django.contrib.auth import get_user_model
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def create_user_settings(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    Settings = apps.get_model('accounts', 'Settings')
    Settings.objects.bulk_create(
        (Settings(user=user) for user in User.objects.all()),
        batch_size=1000,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_created_at_profile_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hide_completed_todos', models.BooleanField(default=False)),
                ('receive_email_reminders', models.BooleanField(default=True)),
                ('default_ordering', models.CharField(choices=[('created_at', 'Oldest'), ('-created_at', 'Newest'), ('priority', 'Priority'), ('name', 'A to Z'), ('-name', 'Z to A'), ('deadline', 'Deadline (earliest)'), ('-deadline', 'Deadline (latest)')], default='created_at', max_length=11)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(create_user_settings, migrations.RunPython.noop, atomic=True)
    ]
