# Generated by Django 4.2.9 on 2024-01-27 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='is_archived',
            new_name='is_trashed',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='is_archived',
            new_name='is_trashed',
        ),
    ]
