# Generated by Django 4.2.9 on 2024-01-29 23:08

from django.db import migrations, models

from .data.quotes import QUOTES


def add_initial_quotes(apps, schema_editor):
    Quote = apps.get_model('quotes', 'Quote')
    quotes = [Quote(text=q['text'], attributed_to=q['attributed_to']) for q in QUOTES]
    Quote.objects.bulk_create(quotes)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('attributed_to', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('?',),
            },
        ),
        migrations.RunPython(add_initial_quotes, migrations.RunPython.noop, atomic=True)
    ]
