# Generated by Django 4.2.9 on 2024-02-02 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quote',
            options={},
        ),
    ]
