# Generated by Django 4.2.9 on 2024-02-03 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def add_email_and_accept_quotes(apps, schema_editor):
    Quote = apps.get_model('quotes', 'Quote')
    Quote.objects.update(submitted_by_email=settings.CONTACT_EMAIL)
    Quote.objects.update(is_accepted=True)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quotes', '0002_alter_quote_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quote',
            name='submitted_by_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='quote',
            name='submitted_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quote',
            name='text',
            field=models.TextField(unique=True),
        ),
        migrations.RunPython(add_email_and_accept_quotes, migrations.RunPython.noop, atomic=True),
    ]
