# Generated by Django 4.2.9 on 2024-02-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_quote_is_accepted_quote_submitted_by_email_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.CheckConstraint(check=models.Q(('submitted_by_email', ''), ('submitted_by_user__isnull', True), _negated=True), name='quote_user_or_email_required', violation_error_message='Please provide an email or login'),
        ),
    ]
